<a href="https://colab.research.google.com/github/salih-salu/Loan_Approval_prediction_Machine_learning/blob/main/Load_approval_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('/content/loan_data_1.csv')

In [22]:
df.isna().sum()

Text                 0
Income               0
Credit_Score         3
Loan_Amount          0
DTI_Ratio            0
Employment_Status    0
Approval             0
dtype: int64

In [23]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
23995    False
23996    False
23997    False
23998    False
23999    False
Length: 24000, dtype: bool

In [24]:
df

,Text,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval
0,I need a loan to pay for an international vaca...,26556,581.0,8314,79.26,employed,Rejected
1,I want to make home improvements like installi...,197392,389.0,111604,22.14,employed,Rejected
2,"I need a loan for home renovation, including a...",44561,523.0,34118,45.44,employed,Rejected
3,I need funds to buy new furniture and applianc...,190363,729.0,118757,10.22,unemployed,Rejected
4,I need a loan to start a small business.,61853,732.0,19210,44.13,employed,Approved
...,...,...,...,...,...,...,...
23995,I need funds to pay for my daughter's college ...,195242,817.0,16403,24.32,employed,Approved
23996,I need financial assistance to launch my own Y...,150246,729.0,101572,9.97,employed,Rejected
23997,I need money to open a small bookstore and café.,64571,650.0,30533,57.35,employed,Rejected
23998,I want to buy a car for my rideshare business ...,115825,418.0,89837,10.37,unemployed,Rejected
23999,I need financial help to cover maternity and d...,180440,769.0,15259,15.06,employed,Approved

In [25]:
df.drop(columns='Text', inplace=True)

In [26]:
df

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval
0,26556,581.0,8314,79.26,employed,Rejected
1,197392,389.0,111604,22.14,employed,Rejected
2,44561,523.0,34118,45.44,employed,Rejected
3,190363,729.0,118757,10.22,unemployed,Rejected
4,61853,732.0,19210,44.13,employed,Approved
...,...,...,...,...,...,...
23995,195242,817.0,16403,24.32,employed,Approved
23996,150246,729.0,101572,9.97,employed,Rejected
23997,64571,650.0,30533,57.35,employed,Rejected
23998,115825,418.0,89837,10.37,unemployed,Rejected
23999,180440,769.0,15259,15.06,employed,Approved

In [27]:
df.isna().sum()

Income               0
Credit_Score         3
Loan_Amount          0
DTI_Ratio            0
Employment_Status    0
Approval             0
dtype: int64

In [28]:
df['Credit_Score'] = df['Credit_Score'].fillna(df['Credit_Score'].mean())

In [29]:
df.isna().sum()

Income               0
Credit_Score         0
Loan_Amount          0
DTI_Ratio            0
Employment_Status    0
Approval             0
dtype: int64

In [30]:
df['Employment_Status'].unique()

array(['employed', 'unemployed'], dtype=object)

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
lb = LabelEncoder()
df['Employment_Status'] = lb.fit_transform(df['Employment_Status'])

In [33]:
df['Approval'] = lb.fit_transform(df['Approval'])

In [34]:
df['Approval'].value_counts()

Approval
1    20067
0     3933
Name: count, dtype: int64

In [37]:
from imblearn.over_sampling import SMOTE